name: Generate 3D Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        with:
          USERNAME: antonbogdan165
          SETTING_JSON: |
            {
              "type": "calendar",
              "theme": "github-dark",
              "background": "#0d1117"
            }

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./profile-3d-contrib
          publish_branch: output
