name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: antonbogdan165
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg

      - name: Add colors + glow
        run: |
          sed -i 's/<svg /<svg style="background:#0d1117; filter: drop-shadow(0 0 8px #00f5d4) drop-shadow(0 0 16px #00f5d4)" /' dist/snake-dark.svg

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
